version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: devops
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - backendNetwork

  backend:
    depends_on:
      - db
    image: mezenbayounes/devops_back_end:1.0.0
    container_name: springbootapp
    restart: on-failure
    ports:
      - 6868:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/devops?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "devops",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backendNetwork

  frontend:
    image: mezenbayounes/devops_front_end:1.0.0
    container_name: angularapp
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  db:

networks:
  backendNetwork: